#!/bin/bash
owner="$1"
repo="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
name="$2"

mv example.go "$repo.go"
mv example_test.go "${repo}_test.go"
mv cmd/example "cmd/$repo"
rm -rf .git
rm -rf script
git init
git remote add origin "git@github.com:$owner/$repo.git"
git add -A
git commit -m 'First commit!'
make setup
